/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary':                  '#9c3f08',
        'primary-container':        '#bc5721',
        'primary-fixed':            '#ffdbcc',
        'primary-fixed-dim':        '#ffb695',
        'on-primary':               '#ffffff',
        'on-primary-fixed':         '#351000',
        'on-primary-fixed-variant': '#7b2f00',
        'on-primary-container':     '#fffbff',
        'secondary':                '#15686f',
        'secondary-container':      '#a6eff6',
        'secondary-fixed':          '#a6eff6',
        'secondary-fixed-dim':      '#8bd2da',
        'on-secondary':             '#ffffff',
        'on-secondary-fixed':       '#002022',
        'on-secondary-fixed-variant':'#004f55',
        'on-secondary-container':   '#1f6e75',
        'tertiary':                 '#765700',
        'tertiary-container':       '#956e00',
        'tertiary-fixed':           '#ffdfa0',
        'tertiary-fixed-dim':       '#f6be39',
        'on-tertiary':              '#ffffff',
        'on-tertiary-fixed':        '#261a00',
        'on-tertiary-fixed-variant':'#5c4300',
        'on-tertiary-container':    '#fffbff',
        'surface':                  '#fff8f4',
        'surface-bright':           '#fff8f4',
        'surface-dim':              '#e2d8d1',
        'surface-variant':          '#eae1da',
        'surface-container':        '#f6ece5',
        'surface-container-low':    '#fcf2eb',
        'surface-container-high':   '#f0e6df',
        'surface-container-highest':'#eae1da',
        'surface-container-lowest': '#ffffff',
        'surface-tint':             '#9f420b',
        'on-surface':               '#1f1b17',
        'on-surface-variant':       '#56423a',
        'inverse-surface':          '#34302b',
        'inverse-on-surface':       '#f9efe8',
        'inverse-primary':          '#ffb695',
        'background':               '#fff8f4',
        'on-background':            '#1f1b17',
        'outline':                  '#8a7268',
        'outline-variant':          '#ddc1b5',
        'error':                    '#ba1a1a',
        'error-container':          '#ffdad6',
        'on-error':                 '#ffffff',
        'on-error-container':       '#93000a',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg:      '0.5rem',
        xl:      '0.75rem',
        '2xl':   '1rem',
        full:    '9999px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
      fontFamily: {
        display: ['"Playfair Display"', 'serif'],
        body:    ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg':        ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg-mobile': ['36px', { lineHeight: '44px', fontWeight: '700' }],
        'headline-lg':       ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'headline-md':       ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg':           ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md':           ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md':          ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        'caption':           ['12px', { lineHeight: '16px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};
